#!/bin/bash                                                                    

# Note: Before running the following script, please make sure to:
# 1.  Create a "qemu_test" directory and then copy in pre-built
#     versions of a53fsb.bin and m4resetA53.bin.  These two files
#     are not generated by the Yocto build process.
# 2.  Run the "yocto_hpsc.sh" script with the "bitbake core-image-minimal"
#     option in order to generate the rest of the needed QEMU files.
 
YOCTO_DEPLOY_DIR=${PWD}/poky/build/tmp/deploy/images/zcu102-zynqmp
YOCTO_QEMU_DIR=${PWD}/poky/build/tmp/work/x86_64-linux/qemu-xilinx-native/v2.8.1-xilinx-v2017.3+gitAUTOINC+3ccd3bdaa4-r0/image/usr/local/bin
QEMU_TEST_DIR=${PWD}/qemu_test

# copy the needed files into the "qemu_test" directory
mkdir -p ${QEMU_TEST_DIR}
cp ${YOCTO_DEPLOY_DIR}/arm-trusted-firmware.elf ${QEMU_TEST_DIR}/bl31.elf
cp ${YOCTO_DEPLOY_DIR}/core-image-minimal-zcu102-zynqmp.cpio.gz.u-boot ${QEMU_TEST_DIR}/hpsc-rootfs.cpio.gz.uboot
cp ${YOCTO_DEPLOY_DIR}/Image ${QEMU_TEST_DIR}/Image
cp ${YOCTO_DEPLOY_DIR}/zynqmp-zcu102.dtb ${QEMU_TEST_DIR}/linux-hpsc.dtb
cp ${YOCTO_DEPLOY_DIR}/qemu-hw-devicetrees/hpsc.dtb ${QEMU_TEST_DIR}/hpsc.dtb
cp ${YOCTO_DEPLOY_DIR}/u-boot.elf ${QEMU_TEST_DIR}/u-boot.elf
cp ${YOCTO_QEMU_DIR}/qemu-system-aarch64 ${QEMU_TEST_DIR}/qemu-system-aarch64

# run QEMU
${QEMU_TEST_DIR}/qemu-system-aarch64 -machine arm-generic-fdt \
    -device loader,file=${QEMU_TEST_DIR}/a53fsb.bin,addr=0xfffff000,cpu-num=0 \
    -nographic -serial mon:stdio -serial null \
    -device loader,addr=0x6000000,file=${QEMU_TEST_DIR}/hpsc-rootfs.cpio.gz.uboot \
    -hw-dtb ${QEMU_TEST_DIR}/hpsc.dtb \
    -device loader,file=${QEMU_TEST_DIR}/bl31.elf,cpu-num=0 \
    -device loader,addr=0x4000000,file=${QEMU_TEST_DIR}/linux-hpsc.dtb \
    -device loader,addr=0x80000,file=${QEMU_TEST_DIR}/Image \
    -device loader,file=${QEMU_TEST_DIR}/u-boot.elf \
    -net nic -net nic -net nic -net nic,vlan=1 -net user,vlan=1,hostfwd=tcp:127.0.0.1:2345-10.0.2.15:2345,hostfwd=tcp:127.0.0.1:10022-10.0.2.15:22 \
    -device loader,file=${QEMU_TEST_DIR}/m4resetA53.bin,cpu-num=10 -s
